apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast
spec:
  replicas: 3
  serviceName: hazelcast
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      containers:
        - name: hazelcast
          image: leszko/hazelcast-enterprise
          imagePullPolicy: Always
          ports:
          - containerPort: 5701
          env:
          - name: HZ_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: hz-license-key
                key: license
          - name: KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keystore-password
                key: password
          - name: JAVA_OPTS
            value: "-Djavax.net.ssl.keyStorePassword=${KEYSTORE_PASSWORD} -Djavax.net.ssl.trustStorePassword=${KEYSTORE_PASSWORD}"

---

apiVersion: v1
kind: Service
metadata:
  name: hazelcast
spec:
  type: ClusterIP
  selector:
    app: hazelcast
  ports:
  - name: hazelcast
    port: 5701